[package]
name = "ruinvest"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8.1"
tokio = { version = "1.36.0", features = ["full"] }
percentage = "0.1.0"
format_num = "0.1.0"
fantoccini = "0.21.2"
serde_json = "1.0.128"
serde = "1.0.210"
serde_derive = "1.0.210"
num-format = "0.4.4"

[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
features=["ttf"]
