[package]
name = "ruinvest"
version = "0.1.0"
edition = "2021"

[dependencies]
percentage = "0.1.0"
ron = "0.8.1"
serde = "1.0.197"
serde_derive = "1.0.197"

[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
features=["ttf"]
