[package]
name = "ruinvest"
version = "0.1.0"
edition = "2021"

[dependencies]
ron = "0.8.1"
serde = "1.0.197"
serde_derive = "1.0.197"
scraper = "0.17.1"
reqwest = { version = "0.11", features = ["blocking"] }
tokio = { version = "1.36.0", features = ["full"] }
percentage = "0.1.0"



[dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
features=["ttf"]
