name: Rust - Fedora

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Container
      uses: gbraad-actions/fedora-action@main
      with:
          dnf-packages: cargo liburing-devel rust-pkg-config-devel openssl-devel openssl rust-openssl-devel pkgconf-pkg-config gcc git-core make cmake alsa-lib-devel pulseaudio-libs-devel pipewire-devel libX11-devel libXext-devel libXrandr-devel libXcursor-devel libXfixes-devel libXi-devel libXScrnSaver-devel dbus-devel ibus-devel systemd-devel mesa-libGL-devel libxkbcommon-devel mesa-libGLES-devel mesa-libEGL-devel vulkan-devel wayland-devel wayland-protocols-devel libdrm-devel mesa-libgbm-devel libusb1-devel libdecor-devel pipewire-jack-audio-connection-kit-devel
          run: |
            clear;
            cargo build;
            cargo clippy;
            cargo test;


