name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Necessary Packages
      run: sudo apt install -y pkg-config cmake build-essential git libfontconfig-dev
    - name: Build The Project
      run: cargo build
    - name: Check Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test
