name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: sudo apt install -y pkg-config cmake build-essential git libfontconfig-dev
    - name: configure cmake 
      run: export CMAKE_ARGS="-DSDL_UNIX_CONSOLE_BUILD=ON" && export CMAKE_C_FLAGS="-DSDL_UNIX_CONSOLE_BUILD=ON"
    - name: Build The Project
      run: CARGO_BUILD_ENV="CMAKE_ARGS=-DSDL_UNIX_CONSOLE_BUILD=ON" && cargo build
    - name: Check Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test
